In [ ]:
#3rd Party Libraries:
    1.Numpy
    2.pandas
    3.Matplotlib
    4.openpxl
    


In [ ]:
#Numpy

In [1]:
import numpy as np

In [3]:
array_one = np.array([1,2,3,4,5])

In [4]:
array_one

array([1, 2, 3, 4, 5])

In [5]:
type(array_one)

numpy.ndarray

In [8]:
numbers = [7,8,9]

In [9]:
array_two = np.array(numbers)

In [10]:
array_two 

array([7, 8, 9])

In [11]:
type(array_two)

numpy.ndarray

In [14]:
test =[2,3]

In [20]:
array_three = np.zeros(test)

In [21]:
array_three

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
array_three = np.zeros(test)

In [25]:
array_three = np.zeros(test)

In [28]:
import numpy as ab

In [29]:
numbers1 = [1,2]

In [30]:
array_test = ab.array(numbers1)

In [31]:
array_test

array([1, 2])

In [32]:
type(array_test)

numpy.ndarray

In [33]:
import numpy as np

In [34]:
value =[3,4]

In [35]:
sarath_array = np.ones(value)

In [36]:
sarath_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
sarath_array = np.zeros(value)

In [38]:
sarath_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
sarath_array = np.eye(3)

In [43]:
sarath_array 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])