In [ ]:
#Iteration through numpy:

In [1]:
import numpy as np;

In [7]:
x =np.array(11)

In [8]:
x

array(11)

In [11]:
type(x)

numpy.ndarray

In [13]:
y =np.array([11])

In [14]:
y

array([11])

In [15]:
type(y)

numpy.ndarray

In [24]:
abc1 =np.arange(11)

In [25]:
abc1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
abc1.shape

(11,)

In [21]:
abc =np.arange(11)**2

In [22]:
abc


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [36]:
for tmp in abc:
    print(tmp**(1/2))

0.0
1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0
3.1622776601683795


In [38]:
Employee= np.array([['sarath','shyam','Anushka','Harsha'],[10,20,30,40],[500,1000,200,2000]])

In [39]:
Employee

array([['sarath', 'shyam', 'Anushka', 'Harsha'],
       ['10', '20', '30', '40'],
       ['500', '1000', '200', '2000']], dtype='<U7')

In [42]:
Employee.shape

(3, 4)

In [43]:
for temp in Employee:
    print("row =", temp )

row = ['sarath' 'shyam' 'Anushka' 'Harsha']
row = ['10' '20' '30' '40']
row = ['500' '1000' '200' '2000']


In [46]:
for temp in Employee.flatten():
    print( temp )

sarath
shyam
Anushka
Harsha
10
20
30
40
500
1000
200
2000


In [54]:
for temp in Employee.flatten(order='F'):
    print( temp )

sarath
10
500
shyam
20
1000
Anushka
30
200
Harsha
40
2000


In [55]:
for temp in Employee.flatten(order='A'):
    print( temp )

sarath
shyam
Anushka
Harsha
10
20
30
40
500
1000
200
2000


In [56]:
for temp in np.nditer(Employee):
    print( temp )

sarath
shyam
Anushka
Harsha
10
20
30
40
500
1000
200
2000


In [57]:
for temp in np.nditer(Employee,order='F'):
    print( temp )

sarath
10
500
shyam
20
1000
Anushka
30
200
Harsha
40
2000


In [58]:
for temp in np.nditer(Employee,order='A'):
    print( temp )

sarath
shyam
Anushka
Harsha
10
20
30
40
500
1000
200
2000


In [59]:
for temp in np.nditer(Employee,order='C'):
    print( temp )

sarath
shyam
Anushka
Harsha
10
20
30
40
500
1000
200
2000
